export { default as HomeView } from './home'
export { default as AboutView } from './about'
export { default as WorkView } from './work'
export { default as WorkDetailView } from './work/detail'
export { default as ContactView } from './contact'
